services:
  mongodb:
    image: mongo:8.0.13
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rag-chatbot
    restart: always
    env_file:
      - ../.env
    environment:
      DB_DOMAIN: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongo_data:
